package_assets: off
gzip_assets: off
compress_assets: off
template_function: _.template

javascripts:
    postswidget:
        - js/underscore.js
        - js/backbone.js
        - jst/*.jst
        - js/widget.js
